# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170e8a1ad634fd9cc4f22b40e5a6655821f245eeea7a2fabe321d10fb5324d4d8dbc1f9cab6f392382f6c2dc7c050a0127fc25a1d8c2978bda85fa53afe953d1

test:
  secret_key_base: 3d080279e72748321f943b64e3c81f4dc820c1ed4a57a1d5e04ad64c8f5ff127160b4374e34ac0c27722e8d462eefe9481d3aa9224383580008f2ed9203d4deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
